In [27]:
from __future__ import division
from __future__ import print_function

import time
import numpy as np
import math

import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
import torch_geometric

from  utils import accuracy
from models import iterativeGCN, MLP_GCN, normalNN, iterativeNN, GCN
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures

In [28]:
dataset = Planetoid(root='data/Planetoid', 
                        name="Cora", 
                        transform=NormalizeFeatures())
data = dataset[0]

In [30]:
torch.count_nonzero(data.x)

tensor(49216)

In [33]:
torch.prod(torch.Tensor([data.x.shape]))

tensor(3880564.)

In [8]:
hid_dim = 16
num_iter_layers = 5
dropout = 0.5
smooth_fac= 0.7

In [9]:
mlp_gcn = MLP_GCN(input_dim=dataset.num_features,
                  output_dim=dataset.num_classes,
                  hidden_dim=hid_dim,
                  num_layers=num_iter_layers,
                  dropout=dropout,
                  xavier_init=True)
norm_nn = normalNN(input_dim=dataset.num_features,
                  output_dim=dataset.num_classes,
                  hidden_dim=hid_dim,
                  num_layers=num_iter_layers,
                  dropout=dropout,
                  xavier_init=True)
iter_gcn = iterativeGCN(input_dim=dataset.num_features,
                  output_dim=dataset.num_classes,
                  hidden_dim=hid_dim,
                  num_train_iter=num_iter_layers,
                  smooth_fac=smooth_fac,
                  dropout=dropout,
                  xavier_init=True)
iter_nn = iterativeNN(input_dim=dataset.num_features,
                  output_dim=dataset.num_classes,
                  hidden_dim=hid_dim,
                  num_train_iter=num_iter_layers,
                  smooth_fac=smooth_fac,
                  dropout=dropout,
                  xavier_init=True)
iter_nn = iterativeNN(input_dim=dataset.num_features,
                  output_dim=dataset.num_classes,
                  hidden_dim=hid_dim,
                  num_train_iter=num_iter_layers,
                  smooth_fac=smooth_fac,
                  dropout=dropout,
                  xavier_init=True)
gcn = GCN(input_dim=dataset.num_features,
                  output_dim=dataset.num_classes,
                  hidden_dim=hid_dim,
                  num_layers=num_iter_layers,
                  dropout=dropout)

In [37]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [36]:
gcn = GCN(input_dim=dataset.num_features,
                  output_dim=dataset.num_classes,
                  hidden_dim=32,
                  num_layers=3,
                  dropout=0.5)

In [38]:
print("usual gcn: ", count_parameters(gcn))

usual gcn:  47175


In [10]:
print("iterative NN: ", count_parameters(iter_nn))
print("normal NN: ", count_parameters(norm_nn))
print("iterative GCN: ", count_parameters(iter_gcn))
print("usual gcn: ", count_parameters(gcn))
print("gcn with mlp: ", count_parameters(mlp_gcn))

iterative NN:  23335
normal NN:  24423
iterative GCN:  23335
usual gcn:  23879
gcn with mlp:  24423


In [11]:
print(gcn)

GCN(
  (first_gc): GCNConv(1433, 16)
  (gcs): ModuleList(
    (0-2): 3 x GCNConv(16, 16)
  )
  (final_gc): GCNConv(16, 7)
)


In [14]:
import numpy as np
full_schedule = np.full(10, 0.5)
print("full schedule: ", full_schedule)
for iter in range(len(full_schedule)):
    eval_schedule = full_schedule[0:iter]
    print("eval schedule: ", eval_schedule)

full schedule:  [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
eval schedule:  []
eval schedule:  [0.5]
eval schedule:  [0.5 0.5]
eval schedule:  [0.5 0.5 0.5]
eval schedule:  [0.5 0.5 0.5 0.5]
eval schedule:  [0.5 0.5 0.5 0.5 0.5]
eval schedule:  [0.5 0.5 0.5 0.5 0.5 0.5]
eval schedule:  [0.5 0.5 0.5 0.5 0.5 0.5 0.5]
eval schedule:  [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
eval schedule:  [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [16]:
aa = F.sigmoid(torch.Tensor(np.linspace(1, 9, 30)))

In [17]:
len(aa)

30

In [23]:
import numpy as np
import torch.nn.functional as F
import torch
F.sigmoid(torch.Tensor(np.linspace(0.5, 4, 60)))

tensor([0.6225, 0.6363, 0.6499, 0.6633, 0.6764, 0.6892, 0.7018, 0.7141, 0.7260,
        0.7377, 0.7490, 0.7600, 0.7706, 0.7809, 0.7909, 0.8006, 0.8099, 0.8188,
        0.8275, 0.8358, 0.8438, 0.8514, 0.8588, 0.8658, 0.8726, 0.8790, 0.8852,
        0.8911, 0.8967, 0.9021, 0.9072, 0.9121, 0.9167, 0.9211, 0.9253, 0.9293,
        0.9331, 0.9367, 0.9402, 0.9434, 0.9465, 0.9494, 0.9522, 0.9548, 0.9573,
        0.9597, 0.9619, 0.9640, 0.9660, 0.9679, 0.9697, 0.9714, 0.9730, 0.9745,
        0.9760, 0.9773, 0.9786, 0.9798, 0.9809, 0.9820])

In [22]:
F.sigmoid(torch.Tensor(np.linspace(0.5, 3, 60)))

tensor([0.6225, 0.6324, 0.6422, 0.6518, 0.6614, 0.6708, 0.6801, 0.6892, 0.6983,
        0.7071, 0.7158, 0.7243, 0.7327, 0.7409, 0.7490, 0.7569, 0.7646, 0.7721,
        0.7795, 0.7867, 0.7937, 0.8006, 0.8072, 0.8138, 0.8201, 0.8263, 0.8323,
        0.8381, 0.8438, 0.8493, 0.8546, 0.8598, 0.8648, 0.8697, 0.8744, 0.8790,
        0.8834, 0.8877, 0.8919, 0.8959, 0.8998, 0.9035, 0.9072, 0.9107, 0.9141,
        0.9173, 0.9205, 0.9235, 0.9265, 0.9293, 0.9321, 0.9347, 0.9372, 0.9397,
        0.9420, 0.9443, 0.9465, 0.9486, 0.9506, 0.9526])

In [18]:
F.sigmoid(torch.Tensor([3]))

tensor([0.9526])

In [26]:
from models import GCN
gcn = GCN(input_dim=1433,
                output_dim=7,
                hidden_dim=32,
                num_layers=10,
                dropout=0.5)
print(gcn)

GCN(
  (first_gc): GCNConv(1433, 32)
  (gcs): ModuleList(
    (0-7): 8 x GCNConv(32, 32)
  )
  (final_gc): GCNConv(32, 7)
)
